### ISSUE TITLE
controller can't start with kubectl

### ISSUE THREAD

**Issue by colinlabs** [AliyunContainerService/alicloud-controller-manager#3]
pending status:

```
ERROR: logging before flag.Parse: I1030 13:18:05.834700       1 alicloud.go:71] Read access ID/secret from cloud config failed, try to use environment settings
```

alicoud-controller-manager.yaml:
```
apiVersion: v1
kind: Secret
metadata:
  name: cloud-config
  namespace: kube-system
data:
  # insert your base64 encoded AliCloud access id and key here, ensure there's no trailing newline:
  # to base64 encode your token run:
  #      echo -n "abc123abc123doaccesstoken" | base64
  access-key-id: "xxxxx"
  access-key-secret: "yyyyyy"
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: alicloud-controller-manager
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: alicloud-controller-manager
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Exists
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        operator: Exists
        key: node.cloudprovider.kubernetes.io/uninitialized
      nodeSelector:
         node-role.kubernetes.io/master: ""
      containers:
      - image: colinlee/alicloud-controller-manager
        name: alicloud-controller-manager
        command:
          - /alicloud-controller-manager
          - --leader-elect=true
          - --allocate-node-cidrs=true
          - --cluster-cidr=172.19.0.0/20
          - --kubeconfig=/etc/kubernetes/kubelet.kubeconfig
        volumeMounts:
        - mountPath: /etc/kubernetes/
          name: k8s
          readOnly: true
        env:
          - name: ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: cloud-config
                key: access-key-id
          - name: ACCESS_KEY_SECRET
            valueFrom:
              secretKeyRef:
                name: cloud-config
                key: access-key-secret
      volumes:
      - name: k8s
        hostPath:
          path: /etc/kubernetes
```
with `docker run` to start , i can run nexte step,in vpc network!
