### ISSUE TITLE
deploy alicloud-controller-manager pod error：alibaba cloud provider could not be initialized

### ISSUE THREAD

**Issue by huyipow** [AliyunContainerService/alicloud-controller-manager#8]
deploy alicloud-controller-manage.yaml pod error:
```
[root@node1 ~]# kubectl  logs  alicloud-controller-manager-8466fff6dc-sw68v -n kube-system
ERROR: logging before flag.Parse: F0621 01:25:58.782353       1 main.go:38] Alibaba cloud provider could not be initialized: could not init cloud provider "alicloud": Alicloud: config must be provided!
```

alicloud-controller-manage.yaml  
```
apiVersion: v1
kind: Secret
metadata:
  name: cloud-config
  namespace: kube-system
data:
  # insert your base64 encoded AliCloud access id and key here, ensure there's no trailing newline:
  #   # to base64 encode your token run:
  #     #      echo -n "abc123abc123doaccesstoken" | base64
  access-key-id: 'TFRBSXpjQmZVQzkwV3F'
  access-key-secret: 'ZGt1d0F0OHUwSUVtd05obU40dXpGTUpSWjhu'

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alicloud-controller-manager
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: alicloud-controller-manager
    spec:
      dnsPolicy: Default
      tolerations:
        # this taint is set by all kubelets running `--cloud-provider=external`
        - key: "node.cloudprovider.kubernetes.io/uninitialized"
          value: "true"
          effect: "NoSchedule"
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/google-containers/alicloud-controller-manager:v1.8.1
        name: alicloud-controller-manager
        command:
          - /alicloud-controller-manager
          # set leader-elect=true if you have more that one replicas
          - --leader-elect=true
          - --allocate-node-cidrs=true
          # set this to what you set to controller-manager or kube-proxy
          - --cluster-cidr=10.233.64.0/18
          # if you want to use a secure endpoint or deploy in a kubeadm deployed cluster, you need to use a kubeconfig instead.
          - --master=10.34.11.12:6443
        env:
          - name: ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: cloud-config
                key: access-key-id
          - name: ACCESS_KEY_SECRET
            valueFrom:
              secretKeyRef:
                name: cloud-config
                key: access-key-secret
```
